#!/usr/bin/env bash

##
# Return abs of $1 in parent directories.
#
findf() {
    _pwd=$PWD
    test / = "$PWD" && return \
            || test -e "$1" && echo "$_pwd/$1" && return \
            || cd .. && findf $1
    cd $_pwd
}
